name: C Build and Test

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define the jobs to run
jobs:
  build:
    # Specify the runner (virtual machine) to use
    runs-on: ubuntu-latest

    # Steps to execute
    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies (e.g., GCC compiler)
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make

      # Build the project
      - name: Build
        run: make

      # Run tests (if applicable)
     # - name: Run tests
    #  run: make test
